version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
        - cypress/run:
            store_artifacts: true
            parallel: true
            parallelism: 2
            group: 2 machines